[tools]
"core:bun" = "latest"
"core:deno" = "latest"
"core:node" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:openai/codex" = "latest"
"aqua:anomalyco/opencode" = "latest"
"aqua:twpayne/chezmoi" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:int128/kubelogin" = "latest"
"aqua:helm/helm" = "latest"
"aqua:fluxcd/flux2" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:starship/starship" = "latest"
"aqua:direnv/direnv" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:casey/just" = "latest"
"aqua:sxyazi/yazi" = "latest"

[bootstrap.packages]
"brew-cask:font-monaspace" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-iosevka-nerd-font" = "latest"
"brew-cask:font-iosevka-term-nerd-font" = "latest"
"brew-cask:font-iosevka-term-slab-nerd-font" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
